### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by child-duckling** [child-duckling/cal-cams#1]
# Main Things
- [ ] Favorite cams
- [x] Text color
- [ ] Test Win / Linux
- [ ] Cams freeze?
- [ ] Auto update
- [x] Icon
- [ ] Packed App Broken

# Extra Stuff
- [x] Discord RP
- [x] Dark/Light Mode
- [x] Cam Window on top
- [x] Transparent Cam Window (Mac)
- [ ] Transparent Cam Window (Win)
- [ ] Transparent Cam Window (Linux)
